### ISSUE TITLE
Enable large-scale testing

### ISSUE THREAD

**Issue by mgrip** [prettier/prettier-php#11]
Now that we've pretty much completed node type coverage, I'd like to keep moving this forward by starting to test some larger open-source projects to uncover outstanding issues. This might already be possible but at least as of now I'm having trouble wrapping my head around how to do that. 
@azz @vjeux @czosel does anyone know if this is possible already with the new plugin api/if not what work needs to be done? I'm guessing we'd ideally want to be able to run via the cli with `--debug-check` enabled on a directory.

**Comment by vjeux** [comment]
If I'm not mistaken, you can do it with

```js
find ../SomePHPProject/ -name '*.php' | xargs ./node_modules/.bin/prettier --plugin=. --debug-check
```

**Comment by vjeux** [comment]
Looks like it's not working :(

```js
Error: Cannot find module 'path-root'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vjeux/random/prettier-php/node_modules/prettier/src/config/resolve-config-editorconfig.js:5:18)
```

@azz any idea why it cannot find this module?

**Comment by azz** [comment]
I thought that dependency was recently removed? Not at a computer right now but as a workaround try `--no-editorconfig`

Cc. @josephfrazier

**Comment by josephfrazier** [comment]
Yes, `path-root` was removed in https://github.com/prettier/prettier/commit/7b211eab24f29148496a885e5d6c87073738710f (https://github.com/prettier/prettier/pull/3559https://github.com/prettier/prettier/pull/3559). Can you make sure that you've checked out the latest `master` and have run `yarn`?

**Comment by azz** [comment]
This repo is locked to https://github.com/prettier/prettier/commit/ee148bfdeda373445ac9b67338cbae3df10a6576 which is a couple of commits later.

**Comment by josephfrazier** [comment]
Oh, I see. I still can't reproduce the issue, though:

```bash
josephfrazier@josephfrazier:~/workspace/prettier-php$ git show -q
commit 9c99b001f42470285858269f8eece53375b148c7 (HEAD -> master, origin/master, origin/HEAD)
Author: Christian Zosel <christian@zosel.ch>
Date:   Mon Jan 1 20:19:01 2018 +0100

    Bump php-parser (#10)
josephfrazier@josephfrazier:~/workspace/prettier-php$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.38s.
josephfrazier@josephfrazier:~/workspace/prettier-php$ grep -R path-root node_modules/prettier
josephfrazier@josephfrazier:~/workspace/prettier-php$ 
```

**Comment by azz** [comment]
It's there for me on a2ef27eb

```
azz at macOS in ~/code/prettier-python on clean-ast
$ git log -1 --oneline
a2ef27eb (HEAD -> clean-ast, upstream/master) Switch to scoped @prettier package (#16)

azz at macOS in ~/code/prettier-python on clean-ast
$ yarn
yarn install v1.0.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.40s.

azz at macOS in ~/code/prettier-python on clean-ast
$ cat node_modules/prettier/src/config/resolve-config-editorconfig.js | grep path-root
const pathRoot = require("path-root");
```

**Comment by josephfrazier** [comment]
Hmm, I wonder if it has something to do with the `yarn` version. I just tried the same thing, and don't see `path-root`:

```bash
josephfrazier@josephfrazier:~/workspace/prettier-python$ git log -1 --oneline
a2ef27e (HEAD -> master, origin/master, origin/HEAD) Switch to scoped @prettier package (#16)
josephfrazier@josephfrazier:~/workspace/prettier-python$ yarn
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.40s.
josephfrazier@josephfrazier:~/workspace/prettier-python$ cat node_modules/prettier/src/config/resolve-config-editorconfig.js | grep path-root
josephfrazier@josephfrazier:~/workspace/prettier-python$ grep version node_modules/prettier/package.json 
  "version": "1.9.2",
josephfrazier@josephfrazier:~/workspace/prettier-python$ grep prettier package.json 
  "name": "@prettier/python",
  "repository": "https://github.com/prettier/prettier-python",
    "prettier": "prettier/prettier#b63c669ed9821a0e0d6918243ef4f4a091b222a9"
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-prettier": "^2.4.0",
    "lint": "prettier src/**/*.js --list-different",
josephfrazier@josephfrazier:~/workspace/prettier-python$ 
```

**Comment by azz** [comment]
Could be - I bumped it to the latest prettier commit and everything works 🤷‍♂️

**Comment by mgrip** [comment]
Sorry so then what's the command to run prettier using the php plugin? When I try this (running from the prettier-php repo)

```
find ../SomePHPProject/ -name '*.php' | xargs ./node_modules/.bin/prettier --plugin=. --debug-check
```
it doesn't seem to recognize it should be using the php plugin

**Comment by azz** [comment]
With debug check you need to explicitly pass `--parser php`

**Comment by mgrip** [comment]
Got it - that worked. Thanks!

**Comment by mgrip** [comment]
Ok so after running on a couple examples most of the differences I'm seeing are around spacing addition/removal, specifically around comments. If I'm understanding this correctly, it seems that's the purpose of "massageAST" (at least for JS) here? https://github.com/prettier/prettier/blob/master/src/common/clean-ast.js#L23 - so that when we compare the before+after AST we don't care about any differences produced by the printer itself?

If that's true, should the plugin API expose a whitelist of node types that should be ignored? Or maybe its own "massageAST" function?

**Comment by vjeux** [comment]
For comments, the parser is putting comments in the AST. I would recommend using prettier logic to attach comments. Comments are really hard to get right and prettier has some pretty good heuristics to deal with them. You can see an example of how to wire it up in the python repo: https://github.com/prettier/prettier-python/pull/9

Otherwise, yes, this is the goal of massageAST.

**Comment by mgrip** [comment]
The plugin can now be run just fine following instructions detailed on the README. Closing out
